import { Poppins } from "next/font/google";
import "@/style/globals.css";
import Navbar from "@/components/Navbar";
import MusicController from "@/components/MusicController/MusicController";
import { AudioProvider } from "@/components/MusicController/AudioContext";
import { NextAuthProvider } from "@/components/NextAuthProvider/NextAuthProvider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Suspense } from "react";
import Loading from "./loading";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Web Streaming Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-gray-950`}>
        <NextAuthProvider>
          <AudioProvider>
            <Navbar />
            <div className="pt-16 pb-24">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
            <MusicController />
          </AudioProvider>
        </NextAuthProvider>
        {/* Defer or lazy-load SpeedInsights if not critical */}
        <SpeedInsights />
      </body>
    </html>
  );
}
